# -*- coding: utf-8 -*-
"""ForestLens.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_dFooN1y6uMcE1SH3p5ScYFoSkveFFoc
"""

import torch
print("GPU available:", torch.cuda.is_available())
print("GPU name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics -q
import ultralytics
print("✓ Ultralytics version:", ultralytics.__version__)

import shutil
from pathlib import Path
from ultralytics import YOLO

# Copy dataset from Drive to local storage first (much faster training)
print("Copying dataset to local storage...")
shutil.copytree(
    '/content/drive/MyDrive/ForestLens/Data/splits',
    '/content/splits',
    dirs_exist_ok=True
)
shutil.copy(
    '/content/drive/MyDrive/ForestLens/Data/dataset.yaml',
    '/content/dataset.yaml'
)
print("✓ Dataset copied locally")

# Update yaml to point to local path
import yaml
with open('/content/dataset.yaml') as f:
    config = yaml.safe_load(f)
config['path'] = '/content/splits'
with open('/content/dataset.yaml', 'w') as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)
print("✓ dataset.yaml updated")

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

results = model.train(
    data    = '/content/dataset.yaml',
    epochs  = 50,
    imgsz   = 640,
    batch   = 16,
    patience= 10,
    project = '/content/drive/MyDrive/ForestLens/runs',
    name    = 'forest_lens',
    device  = 0,
    save         = True,
    save_period  = 5,
)

print("✓ Training complete!")

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

results = model.val(
    data    = '/content/dataset.yaml',
    split   = 'test',
    device  = 0,
)

print("✓ Evaluation complete!")

import cv2
import numpy as np
from pathlib import Path

TEST_IMG_DIR = Path('/content/splits/test/images')
TEST_LBL_DIR = Path('/content/splits/test/labels')

def has_animal_baseline(img_path):
    img = cv2.imread(str(img_path))
    if img is None:
        return False

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Laplacian variance — measures sharpness/content
    lap_var = cv2.Laplacian(gray, cv2.CV_64F).var()

    # Mean brightness
    mean_brightness = np.mean(gray)

    # If image is completely dark/bright/blurry = empty
    if mean_brightness < 10 or mean_brightness > 245 or lap_var < 20:
        return False
    return True

tp = fp = tn = fn = 0
images = list(TEST_IMG_DIR.glob('*.jpg')) + list(TEST_IMG_DIR.glob('*.png'))

for img_path in images:
    lbl_path = TEST_LBL_DIR / (img_path.stem + '.txt')
    gt_animal = lbl_path.exists() and lbl_path.stat().st_size > 0
    pred_animal = has_animal_baseline(img_path)

    if gt_animal and pred_animal:       tp += 1
    elif not gt_animal and pred_animal: fp += 1
    elif gt_animal and not pred_animal: fn += 1
    else:                               tn += 1

precision = tp / (tp + fp) if (tp + fp) > 0 else 0
recall    = tp / (tp + fn) if (tp + fn) > 0 else 0
f1        = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
fpr       = fp / (fp + tn) if (fp + tn) > 0 else 0

print("── Baseline Results (OpenCV Heuristic) ────────")
print(f"  Precision:           {precision:.4f}")
print(f"  Recall:              {recall:.4f}")
print(f"  F1 Score:            {f1:.4f}")
print(f"  False Positive Rate: {fpr:.4f}")
print(f"  TP:{tp} FP:{fp} TN:{tn} FN:{fn}")
print(f"  Total images: {len(images)}")
print("───────────────────────────────────────────────")

from pathlib import Path
import shutil
import random

random.seed(42)

TRAIN_IMG = Path('/content/splits/train/images')
TRAIN_LBL = Path('/content/splits/train/labels')
TEST_IMG  = Path('/content/splits/test/images')
TEST_LBL  = Path('/content/splits/test/labels')

# Find empty frames in train (label file is empty)
empty_frames = []
for lbl in TRAIN_LBL.glob('*.txt'):
    if lbl.stat().st_size == 0:
        img = TRAIN_IMG / (lbl.stem + '.jpg')
        if not img.exists():
            img = TRAIN_IMG / (lbl.stem + '.png')
        if img.exists():
            empty_frames.append((img, lbl))

print(f"Found {len(empty_frames)} empty frames in train")

# Move 150 to test
selected = random.sample(empty_frames, min(150, len(empty_frames)))
for img, lbl in selected:
    shutil.move(str(img), TEST_IMG / img.name)
    shutil.move(str(lbl), TEST_LBL / lbl.name)

print(f"✓ Moved {len(selected)} empty frames to test set")
print(f"Test set now has {len(list(TEST_IMG.glob('*')))} images")

import cv2
import numpy as np
from pathlib import Path

TEST_IMG_DIR = Path('/content/splits/test/images')
TEST_LBL_DIR = Path('/content/splits/test/labels')

def has_animal_baseline(img_path):
    img = cv2.imread(str(img_path))
    if img is None:
        return False
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    lap_var = cv2.Laplacian(gray, cv2.CV_64F).var()
    mean_brightness = np.mean(gray)
    if mean_brightness < 10 or mean_brightness > 245 or lap_var < 20:
        return False
    return True

tp = fp = tn = fn = 0
images = list(TEST_IMG_DIR.glob('*.jpg')) + list(TEST_IMG_DIR.glob('*.png'))

for img_path in images:
    lbl_path = TEST_LBL_DIR / (img_path.stem + '.txt')
    gt_animal = lbl_path.exists() and lbl_path.stat().st_size > 0
    pred_animal = has_animal_baseline(img_path)

    if gt_animal and pred_animal:       tp += 1
    elif not gt_animal and pred_animal: fp += 1
    elif gt_animal and not pred_animal: fn += 1
    else:                               tn += 1

precision = tp / (tp + fp) if (tp + fp) > 0 else 0
recall    = tp / (tp + fn) if (tp + fn) > 0 else 0
f1        = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
fpr       = fp / (fp + tn) if (fp + tn) > 0 else 0

print("── Baseline Results (OpenCV Heuristic) ────────")
print(f"  Precision:           {precision:.4f}")
print(f"  Recall:              {recall:.4f}")
print(f"  F1 Score:            {f1:.4f}")
print(f"  False Positive Rate: {fpr:.4f}")
print(f"  TP:{tp} FP:{fp} TN:{tn} FN:{fn}")
print(f"  Total images: {len(images)}")
print("───────────────────────────────────────────────")

from ultralytics import YOLO
from pathlib import Path

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

TEST_IMG_DIR = Path('/content/splits/test/images')
TEST_LBL_DIR = Path('/content/splits/test/labels')

images = list(TEST_IMG_DIR.glob('*.jpg')) + list(TEST_IMG_DIR.glob('*.png'))

tp = fp = tn = fn = 0

for img_path in images:
    lbl_path = TEST_LBL_DIR / (img_path.stem + '.txt')
    gt_animal = lbl_path.exists() and lbl_path.stat().st_size > 0

    result = model.predict(str(img_path), conf=0.35, verbose=False)[0]
    pred_animal = len(result.boxes) > 0

    if gt_animal and pred_animal:       tp += 1
    elif not gt_animal and pred_animal: fp += 1
    elif gt_animal and not pred_animal: fn += 1
    else:                               tn += 1

precision = tp / (tp + fp) if (tp + fp) > 0 else 0
recall    = tp / (tp + fn) if (tp + fn) > 0 else 0
f1        = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
fpr       = fp / (fp + tn) if (fp + tn) > 0 else 0

print("── YOLOv8 Binary Results ───────────────────────")
print(f"  Precision:           {precision:.4f}")
print(f"  Recall:              {recall:.4f}")
print(f"  F1 Score:            {f1:.4f}")
print(f"  False Positive Rate: {fpr:.4f}")
print(f"  TP:{tp} FP:{fp} TN:{tn} FN:{fn}")
print(f"  Total images: {len(images)}")
print("───────────────────────────────────────────────")

import json
from pathlib import Path

results = {
    "baseline": {
        "precision": 0.8969,
        "recall": 1.0000,
        "f1": 0.9456,
        "false_positive_rate": 1.0000,
        "tp": 548, "fp": 63, "tn": 0, "fn": 0
    },
    "yolov8": {
        "precision": 0.9444,
        "recall": 0.8686,
        "f1": 0.9049,
        "false_positive_rate": 0.4444,
        "tp": 476, "fp": 28, "tn": 35, "fn": 72,
        "mAP50": 0.940,
        "per_class": {
            "deer":     {"precision": 0.955, "recall": 0.849, "mAP50": 0.933},
            "boar":     {"precision": 0.894, "recall": 0.824, "mAP50": 0.920},
            "rabbit":   {"precision": 0.887, "recall": 0.920, "mAP50": 0.963},
            "jackal":   {"precision": 0.973, "recall": 0.807, "mAP50": 0.899},
            "pheasant": {"precision": 0.978, "recall": 0.928, "mAP50": 0.982},
        }
    }
}

out = Path('/content/drive/MyDrive/ForestLens/evaluation_results.json')
with open(out, 'w') as f:
    json.dump(results, f, indent=2)

print("✓ Results saved to Google Drive")

from ultralytics import YOLO
import matplotlib.pyplot as plt

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

results = model.predict(
    source='/content/Timing_is_everthying.jpg',
    conf=0.35,
    verbose=False
)

result = results[0]
print(f"Detections: {len(result.boxes)}")
for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

plt.figure(figsize=(10, 8))
plt.imshow(result.plot()[:,:,::-1])
plt.axis('off')
plt.show()

from ultralytics import YOLO
import matplotlib.pyplot as plt
from pathlib import Path
import random

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

# Pick 3 random images from test set
test_images = list(Path('/content/splits/test/images').glob('*.jpg'))
samples = random.sample(test_images, 3)

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

for i, img_path in enumerate(samples):
    results = model.predict(str(img_path), conf=0.35, verbose=False)
    result = results[0]

    detections = [(model.names[int(b.cls[0])], float(b.conf[0])) for b in result.boxes]
    print(f"Image {i+1}: {img_path.name}")
    print(f"  Detections: {detections if detections else 'none'}")

    axes[i].imshow(result.plot()[:,:,::-1])
    axes[i].axis('off')

plt.tight_layout()
plt.show()

from ultralytics import YOLO
import matplotlib.pyplot as plt

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

results = model.predict(
    source='/content/old-trail-cam-pictures-v0-0qpthsagditc1.jpg',
    conf=0.35,
    verbose=False
)

result = results[0]
print(f"Detections: {len(result.boxes)}")
for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

plt.figure(figsize=(10, 8))
plt.imshow(result.plot()[:,:,::-1])
plt.axis('off')
plt.show()

from ultralytics import YOLO
import matplotlib.pyplot as plt
import cv2

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

img_path = '/content/old-trail-cam-pictures-v0-0qpthsagditc1.jpg'

# Try with very low confidence
results = model.predict(
    source=img_path,
    conf=0.01,  # extremely low
    verbose=False
)

result = results[0]
print(f"Detections at conf=0.01: {len(result.boxes)}")
for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

plt.figure(figsize=(10, 8))
plt.imshow(result.plot()[:,:,::-1])
plt.axis('off')
plt.show()

results = model.predict(
    source='/content/old-trail-cam-pictures-v0-0qpthsagditc1.jpg',
    conf=0.01,
    imgsz=1280,  # match the image resolution
    verbose=False
)

result = results[0]
print(f"Detections: {len(result.boxes)}")
for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 8))
plt.imshow(result.plot()[:,:,::-1])
plt.axis('off')
plt.show()

from ultralytics import YOLO
import matplotlib.pyplot as plt

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

results = model.predict(
    source='/content/hq720.jpg',
    conf=0.35,
    verbose=False
)

result = results[0]
print(f"Detections: {len(result.boxes)}")
for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

plt.figure(figsize=(10, 8))
plt.imshow(result.plot()[:,:,::-1])
plt.axis('off')
plt.show()

results = model.predict(
    source='/content/hq720.jpg',
    conf=0.01,
    verbose=False
)

result = results[0]
print(f"Detections at conf=0.01: {len(result.boxes)}")
for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics -q
from ultralytics import YOLO
model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')
print("✓ Model ready")

from ultralytics import YOLO
import matplotlib.pyplot as plt

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

results = model.predict(
    source='/content/frame_0016_jpg.rf.15d92468a070282b521e55f6d82d31e9.jpg',
    conf=0.35,
    verbose=False
)

result = results[0]
print(f"Detections: {len(result.boxes)}")
for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

plt.figure(figsize=(10, 8))
plt.imshow(result.plot()[:,:,::-1])
plt.axis('off')
plt.show()

from ultralytics import YOLO
import matplotlib.pyplot as plt

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

results = model.predict(
    source='/content/20241030-RCNX1477.webp',
    conf=0.35,
    verbose=False
)

result = results[0]
print(f"Detections: {len(result.boxes)}")
for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

plt.figure(figsize=(10, 8))
plt.imshow(result.plot()[:,:,::-1])
plt.axis('off')
plt.show()

from ultralytics import YOLO
import matplotlib.pyplot as plt

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

results = model.predict(
    source='/content/2022.03.18-Night-compilation.jpg',
    conf=0.35,
    verbose=False
)

result = results[0]
print(f"Detections: {len(result.boxes)}")
for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

plt.figure(figsize=(12, 8))
plt.imshow(result.plot()[:,:,::-1])
plt.axis('off')
plt.show()

from ultralytics import YOLO
import matplotlib.pyplot as plt

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

results = model.predict(
    source='/content/Infrared-image-of-a-Hainan-rabbit.jpg',
    conf=0.35,
    verbose=False
)

result = results[0]
print(f"Detections: {len(result.boxes)}")
for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

plt.figure(figsize=(12, 8))
plt.imshow(result.plot()[:,:,::-1])
plt.axis('off')
plt.show()

from ultralytics import YOLO
import matplotlib.pyplot as plt
from pathlib import Path
import random

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

test_images = list(Path('/content/splits/test/images').glob('*.jpg'))
samples = random.sample(test_images, 20)

for i, img_path in enumerate(samples):
    results = model.predict(str(img_path), conf=0.35, verbose=False)
    result = results[0]

    detections = [(model.names[int(b.cls[0])], f"{float(b.conf[0]):.0%}") for b in result.boxes]

    plt.figure(figsize=(10, 6))
    plt.imshow(result.plot()[:,:,::-1])
    plt.axis('off')
    plt.title(f"Image {i+1}: {detections if detections else 'empty frame'}")
    plt.show()

import shutil
from pathlib import Path

shutil.copytree('/content/drive/MyDrive/ForestLens/Data/splits/test',
                '/content/splits/test',
                dirs_exist_ok=True)

test_images = list(Path('/content/splits/test/images').glob('*.jpg'))
print(f"Found {len(test_images)} test images")

from ultralytics import YOLO
import matplotlib.pyplot as plt
from pathlib import Path
import random

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

test_images = list(Path('/content/splits/test/images').glob('*.jpg'))
samples = random.sample(test_images, 20)

for i, img_path in enumerate(samples):
    results = model.predict(str(img_path), conf=0.35, verbose=False)
    result = results[0]

    detections = [(model.names[int(b.cls[0])], f"{float(b.conf[0]):.0%}") for b in result.boxes]

    plt.figure(figsize=(10, 6))
    plt.imshow(result.plot()[:,:,::-1])
    plt.axis('off')
    plt.title(f"Image {i+1}: {detections if detections else 'empty frame'}")
    plt.show()

