# -*- coding: utf-8 -*-
"""ModelTuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IseVMoiIQdiCF4Bq_uUBnxqVC7gW9-O9
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics -q

import shutil
shutil.copytree('/content/drive/MyDrive/ForestLens/Data/splits', '/content/splits', dirs_exist_ok=True)
print("✓ Data ready")

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from collections import Counter

SPLITS_DIR = Path('/content/splits')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

# Count annotations per class per split
all_counts = {}
image_counts = {}

for split in ['train', 'val', 'test']:
    lbl_dir = SPLITS_DIR / split / 'labels'
    img_dir = SPLITS_DIR / split / 'images'

    class_counts = Counter()
    empty = 0

    for lf in lbl_dir.glob('*.txt'):
        content = lf.read_text().strip()
        if not content:
            empty += 1
        else:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    all_counts[split] = class_counts
    image_counts[split] = len(list(img_dir.glob('*.jpg')))

    print(f"\n[{split.upper()}] {image_counts[split]} images")
    for cid, cnt in sorted(class_counts.items()):
        print(f"  {CLASS_NAMES[cid]:10s}: {cnt} annotations")
    print(f"  {'empty':10s}: {empty} frames")

# Plot class distribution
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

for i, split in enumerate(['train', 'val', 'test']):
    species = [CLASS_NAMES[k] for k in sorted(all_counts[split].keys())]
    counts  = [all_counts[split][k] for k in sorted(all_counts[split].keys())]

    bars = axes[i].bar(species, counts, color=['#2196F3','#4CAF50','#FF9800','#F44336','#9C27B0'])
    axes[i].set_title(f'{split.upper()} — {image_counts[split]} images')
    axes[i].set_ylabel('Annotations')
    axes[i].tick_params(axis='x', rotation=45)

    for bar, count in zip(bars, counts):
        axes[i].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 20,
                    str(count), ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/ForestLens/eda_class_distribution.png', dpi=150)
plt.show()
print("✓ EDA chart saved to Google Drive")

import shutil
import random
from pathlib import Path

random.seed(42)

SPLITS_DIR = Path('/content/splits')
BALANCED_DIR = Path('/content/balanced')
TARGET = 1200

# Create balanced directory structure
for split in ['train', 'val', 'test']:
    (BALANCED_DIR / split / 'images').mkdir(parents=True, exist_ok=True)
    (BALANCED_DIR / split / 'labels').mkdir(parents=True, exist_ok=True)

CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

def get_images_by_class(split):
    img_dir = SPLITS_DIR / split / 'images'
    lbl_dir = SPLITS_DIR / split / 'labels'

    by_class = {i: [] for i in range(5)}
    empty = []

    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        img = img_dir / (lbl.stem + '.jpg')
        if not img.exists():
            continue
        if not content:
            empty.append((img, lbl))
        else:
            classes = set(int(l.split()[0]) for l in content.split('\n') if l.strip())
            primary = min(classes)
            by_class[primary].append((img, lbl))

    return by_class, empty

def copy_pair(img, lbl, dst_img_dir, dst_lbl_dir, new_name=None):
    name = new_name or img.name
    shutil.copy2(img, dst_img_dir / name)
    shutil.copy2(lbl, dst_lbl_dir / (Path(name).stem + '.txt'))

print("Processing train split...")
by_class, empty = get_images_by_class('train')

dst_img = BALANCED_DIR / 'train' / 'images'
dst_lbl = BALANCED_DIR / 'train' / 'labels'

for cid, imgs in by_class.items():
    species = CLASS_NAMES[cid]

    if len(imgs) > TARGET:
        # Downsample
        selected = random.sample(imgs, TARGET)
        print(f"  {species:10s}: downsampled {len(imgs)} → {TARGET}")
    else:
        # Keep all
        selected = imgs
        print(f"  {species:10s}: keeping all {len(imgs)}")

    for img, lbl in selected:
        copy_pair(img, lbl, dst_img, dst_lbl)

# Copy empty frames
for img, lbl in empty:
    copy_pair(img, lbl, dst_img, dst_lbl)
print(f"  {'empty':10s}: copied {len(empty)} frames")

print("\n✓ Downsampling done!")

import cv2
import numpy as np
from pathlib import Path
import random

random.seed(42)

BALANCED_DIR = Path('/content/balanced')
dst_img = BALANCED_DIR / 'train' / 'images'
dst_lbl = BALANCED_DIR / 'train' / 'labels'

CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}
TARGET = 1200

def augment_image(img):
    aug = img.copy()
    choice = random.randint(0, 3)
    if choice == 0:
        factor = random.uniform(0.6, 1.4)
        aug = np.clip(aug * factor, 0, 255).astype(np.uint8)
    elif choice == 1:
        mean = np.mean(aug)
        factor = random.uniform(0.7, 1.3)
        aug = np.clip((aug - mean) * factor + mean, 0, 255).astype(np.uint8)
    elif choice == 2:
        noise = np.random.normal(0, 10, aug.shape).astype(np.int16)
        aug = np.clip(aug.astype(np.int16) + noise, 0, 255).astype(np.uint8)
    elif choice == 3:
        h, w = aug.shape[:2]
        angle = random.uniform(-10, 10)
        M = cv2.getRotationMatrix2D((w//2, h//2), angle, 1.0)
        aug = cv2.warpAffine(aug, M, (w, h))
    return aug

def flip_labels(lbl_path):
    content = lbl_path.read_text().strip()
    if not content:
        return content
    lines = []
    for line in content.split('\n'):
        if not line.strip():
            continue
        parts = line.split()
        parts[1] = str(round(1 - float(parts[1]), 6))
        lines.append(' '.join(parts))
    return '\n'.join(lines)

def get_class_images(target_class):
    result = []
    for lbl in dst_lbl.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            continue
        classes = [int(l.split()[0]) for l in content.split('\n') if l.strip()]
        if target_class in classes:
            img = dst_img / (lbl.stem + '.jpg')
            if img.exists():
                result.append((img, lbl))
    return result

# Augment rabbit, jackal, pheasant
for target_class in [2, 3, 4]:
    species = CLASS_NAMES[target_class]
    existing = get_class_images(target_class)
    current = len(existing)
    needed = TARGET - current

    if needed <= 0:
        print(f"{species}: already at {current}, no augmentation needed")
        continue

    print(f"\n{species}: {current} images, generating {needed} more...")
    aug_count = 0

    while aug_count < needed:
        src_img_path, src_lbl_path = random.choice(existing)
        img = cv2.imread(str(src_img_path))
        if img is None:
            continue

        # Random augmentation
        aug = augment_image(img)

        # Random horizontal flip
        flip = random.random() > 0.5
        if flip:
            aug = cv2.flip(aug, 1)
            lbl_content = flip_labels(src_lbl_path)
        else:
            lbl_content = src_lbl_path.read_text().strip()

        new_name = f"aug_{species}_{aug_count}.jpg"
        cv2.imwrite(str(dst_img / new_name), aug)
        (dst_lbl / f"aug_{species}_{aug_count}.txt").write_text(lbl_content)

        aug_count += 1

    print(f"  ✓ {species}: {current} → {current + aug_count}")

print("\n✓ Augmentation complete!")

import shutil
from pathlib import Path
from collections import Counter

SPLITS_DIR = Path('/content/splits')
BALANCED_DIR = Path('/content/balanced')

# Copy val and test unchanged
for split in ['val', 'test']:
    shutil.copytree(
        SPLITS_DIR / split,
        BALANCED_DIR / split,
        dirs_exist_ok=True
    )
print("✓ Val and test copied")

# Verify final counts
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

print("\n── Final Balanced Dataset ──────────────────")
for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'

    images = list(img_dir.glob('*.jpg'))
    class_counts = Counter()
    empty = 0

    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            empty += 1
        else:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    print(f"\n[{split.upper()}] {len(images)} images")
    for cid, cnt in sorted(class_counts.items()):
        print(f"  {CLASS_NAMES[cid]:10s}: {cnt} annotations")
    print(f"  {'empty':10s}: {empty} frames")

print("\n───────────────────────────────────────────")

from pathlib import Path
from ultralytics import YOLO

BALANCED_DIR = Path('/content/balanced')
lbl_dir = BALANCED_DIR / 'train' / 'labels'
img_dir = BALANCED_DIR / 'train' / 'images'

# Count empty frames
empty_frames = [f for f in lbl_dir.glob('*.txt') if f.stat().st_size == 0]
print(f"Current empty frames in train: {len(empty_frames)}")

# Use model to check if any empty frames actually have animals
model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

mislabeled = []
for lbl in empty_frames:
    img = img_dir / (lbl.stem + '.jpg')
    if not img.exists():
        continue
    result = model.predict(str(img), conf=0.5, verbose=False)[0]
    if len(result.boxes) > 0:
        mislabeled.append((img, lbl))

print(f"Mislabeled empty frames (actually have animals): {len(mislabeled)}")

import shutil

# Step 1 — Remove mislabeled empty frames
print(f"Removing {len(mislabeled)} mislabeled empty frames...")
for img, lbl in mislabeled:
    img.unlink()
    lbl.unlink()
print(f"✓ Removed. Clean empty frames remaining: {63 - len(mislabeled)}")

# Step 2 — Add more empty frames from original raw datasets
RAW_DIR = Path('/content/drive/MyDrive/ForestLens/Data/raw')
dst_img = BALANCED_DIR / 'train' / 'images'
dst_lbl = BALANCED_DIR / 'train' / 'labels'

added = 0
TARGET_EMPTY = 500

for dataset in ['Boar-Deer-Hare-Coyote', 'hare', 'Coyote', 'pheasant']:
    lbl_src = RAW_DIR / dataset / 'train' / 'labels'
    img_src = RAW_DIR / dataset / 'train' / 'images'

    if not lbl_src.exists():
        continue

    for lbl in lbl_src.glob('*.txt'):
        if added >= TARGET_EMPTY:
            break
        if lbl.stat().st_size == 0:
            img = img_src / (lbl.stem + '.jpg')
            if not img.exists():
                img = img_src / (lbl.stem + '.png')
            if img.exists():
                new_name = f"empty_{dataset}_{lbl.stem}.jpg"
                shutil.copy2(img, dst_img / new_name)
                (dst_lbl / (new_name.replace('.jpg', '.txt'))).write_text('')
                added += 1

print(f"✓ Added {added} empty frames from raw datasets")
print(f"Total empty frames now: {63 - len(mislabeled) + added}")

import cv2
import numpy as np
from pathlib import Path
from tqdm import tqdm

BALANCED_DIR = Path('/content/balanced')
img_dir = BALANCED_DIR / 'train' / 'images'

images = list(img_dir.glob('*.jpg'))
print(f"Normalizing {len(images)} images...")

for img_path in tqdm(images):
    img = cv2.imread(str(img_path))
    if img is None:
        continue

    # Convert to LAB color space
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    l, a, b = cv2.split(lab)

    # Apply CLAHE to L channel only (brightness normalization)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    l = clahe.apply(l)

    # Merge and convert back
    lab = cv2.merge([l, a, b])
    normalized = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)

    cv2.imwrite(str(img_path), normalized)

print("✓ Homogeneity normalization complete!")

import shutil
import random
import cv2
import numpy as np
from pathlib import Path
from collections import Counter

random.seed(42)

SPLITS_DIR = Path('/content/splits')
BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}
VAL_TARGET = 150

dst_img = BALANCED_DIR / 'val' / 'images'
dst_lbl = BALANCED_DIR / 'val' / 'labels'

# Get source images from original val split
def get_source_images(target_class):
    img_dir = SPLITS_DIR / 'val' / 'images'
    lbl_dir = SPLITS_DIR / 'val' / 'labels'
    result = []
    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            continue
        classes = [int(l.split()[0]) for l in content.split('\n') if l.strip()]
        if target_class in classes:
            img = img_dir / (lbl.stem + '.jpg')
            if img.exists():
                result.append((img, lbl))
    return result

# Count current annotations per class in balanced val
def count_class(target_class):
    count = 0
    for lbl in dst_lbl.glob('*.txt'):
        content = lbl.read_text().strip()
        if content and any(int(l.split()[0]) == target_class
                          for l in content.split('\n') if l.strip()):
            count += 1
    return count

def augment_image(img):
    choice = random.randint(0, 2)
    if choice == 0:
        factor = random.uniform(0.7, 1.3)
        return np.clip(img * factor, 0, 255).astype(np.uint8)
    elif choice == 1:
        noise = np.random.normal(0, 8, img.shape).astype(np.int16)
        return np.clip(img.astype(np.int16) + noise, 0, 255).astype(np.uint8)
    else:
        h, w = img.shape[:2]
        angle = random.uniform(-10, 10)
        M = cv2.getRotationMatrix2D((w//2, h//2), angle, 1.0)
        return cv2.warpAffine(img, M, (w, h))

def flip_labels(lbl_path):
    lines = []
    for line in lbl_path.read_text().strip().split('\n'):
        if not line.strip():
            continue
        parts = line.split()
        parts[1] = str(round(1 - float(parts[1]), 6))
        lines.append(' '.join(parts))
    return '\n'.join(lines)

# Print current val distribution
print("Current val distribution:")
for cid in range(5):
    print(f"  {CLASS_NAMES[cid]:10s}: {count_class(cid)}")

# Augment underrepresented classes
for target_class in [2, 3, 4]:  # rabbit, jackal, pheasant
    species = CLASS_NAMES[target_class]
    current = count_class(target_class)
    needed = VAL_TARGET - current

    if needed <= 0:
        print(f"\n{species}: already at {current}, skipping")
        continue

    sources = get_source_images(target_class)
    if not sources:
        print(f"\n{species}: no source images found")
        continue

    print(f"\n{species}: {current} → adding {needed} more")
    aug_count = 0

    while aug_count < needed:
        src_img_path, src_lbl_path = random.choice(sources)
        img = cv2.imread(str(src_img_path))
        if img is None:
            continue

        flip = random.random() > 0.5
        aug = augment_image(img)
        if flip:
            aug = cv2.flip(aug, 1)
            lbl_content = flip_labels(src_lbl_path)
        else:
            lbl_content = src_lbl_path.read_text().strip()

        new_name = f"val_aug_{species}_{aug_count}.jpg"
        cv2.imwrite(str(dst_img / new_name), aug)
        (dst_lbl / f"val_aug_{species}_{aug_count}.txt").write_text(lbl_content)
        aug_count += 1

    print(f"  ✓ {species}: {current} → {current + aug_count}")

print("\n✓ Val balancing complete!")

import random
from pathlib import Path

random.seed(42)

BALANCED_DIR = Path('/content/balanced')
dst_img = BALANCED_DIR / 'val' / 'images'
dst_lbl = BALANCED_DIR / 'val' / 'labels'

CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}
VAL_TARGET = 150

def get_images_by_class(target_class):
    result = []
    for lbl in dst_lbl.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            continue
        classes = [int(l.split()[0]) for l in content.split('\n') if l.strip()]
        if target_class in classes:
            img = dst_img / (lbl.stem + '.jpg')
            if img.exists():
                result.append((img, lbl))
    return result

for target_class in [0, 1]:  # deer, boar
    species = CLASS_NAMES[target_class]
    images = get_images_by_class(target_class)
    current = len(images)

    if current <= VAL_TARGET:
        print(f"{species}: already at {current}, skipping")
        continue

    # Randomly select images to remove
    to_remove = random.sample(images, current - VAL_TARGET)
    for img, lbl in to_remove:
        img.unlink()
        lbl.unlink()

    print(f"✓ {species}: {current} → {VAL_TARGET}")

print("\n✓ Val downsampling done!")

import shutil
import yaml
from pathlib import Path
from collections import Counter

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

# Verify final counts
print("── Final Balanced Dataset ──────────────────")
for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'

    images = list(img_dir.glob('*.jpg'))
    class_counts = Counter()
    empty = 0

    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            empty += 1
        else:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    print(f"\n[{split.upper()}] {len(images)} images")
    for cid, cnt in sorted(class_counts.items()):
        print(f"  {CLASS_NAMES[cid]:10s}: {cnt}")
    print(f"  {'empty':10s}: {empty}")

print("\n───────────────────────────────────────────")

# Save to Google Drive
print("\nSaving to Google Drive...")
shutil.copytree(
    '/content/balanced',
    '/content/drive/MyDrive/ForestLens/Data/balanced',
    dirs_exist_ok=True
)

# Write dataset.yaml
config = {
    'path': '/content/balanced',
    'train': 'train/images',
    'val':   'val/images',
    'test':  'test/images',
    'nc': 5,
    'names': {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}
}

with open('/content/balanced_dataset.yaml', 'w') as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)

shutil.copy(
    '/content/balanced_dataset.yaml',
    '/content/drive/MyDrive/ForestLens/Data/balanced_dataset.yaml'
)

print("✓ Everything saved to Google Drive")

import shutil
import random
import cv2
from pathlib import Path

random.seed(42)

BALANCED_DIR = Path('/content/balanced')
RAW_DIR = Path('/content/drive/MyDrive/ForestLens/Data/raw')

# Add empty frames to val (100) and test (100)
for split, target in [('val', 100), ('test', 100)]:
    dst_img = BALANCED_DIR / split / 'images'
    dst_lbl = BALANCED_DIR / split / 'labels'

    added = 0
    for dataset in ['Boar-Deer-Hare-Coyote', 'hare', 'Coyote', 'pheasant']:
        if added >= target:
            break

        # Use valid split from original dataset
        src_split = 'valid' if split == 'val' else split
        lbl_src = RAW_DIR / dataset / src_split / 'labels'
        img_src = RAW_DIR / dataset / src_split / 'images'

        if not lbl_src.exists():
            continue

        for lbl in lbl_src.glob('*.txt'):
            if added >= target:
                break
            if lbl.stat().st_size == 0:
                img = img_src / (lbl.stem + '.jpg')
                if not img.exists():
                    img = img_src / (lbl.stem + '.png')
                if img.exists():
                    new_name = f"empty_{split}_{dataset}_{lbl.stem}.jpg"
                    shutil.copy2(img, dst_img / new_name)
                    (dst_lbl / new_name.replace('.jpg', '.txt')).write_text('')
                    added += 1

    print(f"✓ Added {added} empty frames to {split}")

print("\n✓ Empty frames added to val and test!")

from pathlib import Path
from collections import Counter

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

print("── Final Balanced Dataset Verification ─────")
total_images = 0

for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'

    images = list(img_dir.glob('*.jpg'))
    class_counts = Counter()
    empty = 0

    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            empty += 1
        else:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    print(f"\n[{split.upper()}] {len(images)} images")
    for cid, cnt in sorted(class_counts.items()):
        print(f"  {CLASS_NAMES[cid]:10s}: {cnt}")
    print(f"  {'empty':10s}: {empty}")
    total_images += len(images)

print(f"\nTOTAL: {total_images} images")
print("────────────────────────────────────────────")

import shutil
import random
from pathlib import Path

random.seed(99)

BALANCED_DIR = Path('/content/balanced')
RAW_DIR = Path('/content/drive/MyDrive/ForestLens/Data/raw')

dst_img = BALANCED_DIR / 'test' / 'images'
dst_lbl = BALANCED_DIR / 'test' / 'labels'

# Check what we already added to avoid duplicates
existing_names = {f.name for f in dst_img.glob('empty_test_*.jpg')}

added = 0
TARGET = 100

for dataset in ['Boar-Deer-Hare-Coyote', 'hare', 'Coyote', 'pheasant']:
    if added >= TARGET:
        break

    lbl_src = RAW_DIR / dataset / 'test' / 'labels'
    img_src = RAW_DIR / dataset / 'test' / 'images'

    if not lbl_src.exists():
        # Try train as fallback
        lbl_src = RAW_DIR / dataset / 'train' / 'labels'
        img_src = RAW_DIR / dataset / 'train' / 'images'

    if not lbl_src.exists():
        continue

    empty_files = [l for l in lbl_src.glob('*.txt') if l.stat().st_size == 0]
    random.shuffle(empty_files)

    for lbl in empty_files:
        if added >= TARGET:
            break
        img = img_src / (lbl.stem + '.jpg')
        if not img.exists():
            img = img_src / (lbl.stem + '.png')
        if not img.exists():
            continue

        new_name = f"empty_test_{dataset}_{lbl.stem}.jpg"
        if new_name in existing_names:
            continue

        shutil.copy2(img, dst_img / new_name)
        (dst_lbl / new_name.replace('.jpg', '.txt')).write_text('')
        added += 1

print(f"✓ Added {added} empty frames to test")
print(f"Total test empty frames now: {17 + added}")

import shutil
import random
from pathlib import Path

random.seed(42)

BALANCED_DIR = Path('/content/balanced')

train_img = BALANCED_DIR / 'train' / 'images'
train_lbl = BALANCED_DIR / 'train' / 'labels'
test_img  = BALANCED_DIR / 'test' / 'images'
test_lbl  = BALANCED_DIR / 'test' / 'labels'

# Find empty frames in train
empty_in_train = []
for lbl in train_lbl.glob('*.txt'):
    if lbl.stat().st_size == 0:
        img = train_img / (lbl.stem + '.jpg')
        if img.exists():
            empty_in_train.append((img, lbl))

print(f"Empty frames in train: {len(empty_in_train)}")

# Move 30 to test (17 + 30 = 47, same as val)
to_move = random.sample(empty_in_train, 30)
for img, lbl in to_move:
    shutil.move(str(img), test_img / img.name)
    shutil.move(str(lbl), test_lbl / lbl.name)

print(f"✓ Moved 30 empty frames to test")
print(f"Train empty frames remaining: {len(empty_in_train) - 30}")
print(f"Test empty frames now: 47")

import shutil
import random
from pathlib import Path

random.seed(42)

BALANCED_DIR = Path('/content/balanced')

train_img = BALANCED_DIR / 'train' / 'images'
train_lbl = BALANCED_DIR / 'train' / 'labels'
test_img  = BALANCED_DIR / 'test' / 'images'
test_lbl  = BALANCED_DIR / 'test' / 'labels'

# Find empty frames in train
empty_in_train = []
for lbl in train_lbl.glob('*.txt'):
    if lbl.stat().st_size == 0:
        img = train_img / (lbl.stem + '.jpg')
        if img.exists():
            empty_in_train.append((img, lbl))

print(f"Empty frames in train: {len(empty_in_train)}")

# Move 30 to test (17 + 30 = 47, same as val)
to_move = random.sample(empty_in_train, 30)
for img, lbl in to_move:
    shutil.move(str(img), test_img / img.name)
    shutil.move(str(lbl), test_lbl / lbl.name)

print(f"✓ Moved 30 empty frames to test")
print(f"Train empty frames remaining: {len(empty_in_train) - 30}")
print(f"Test empty frames now: 47")

from pathlib import Path
from collections import Counter

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

print("── Final Balanced Dataset Verification ─────")
total_images = 0

for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'

    images = list(img_dir.glob('*.jpg'))
    class_counts = Counter()
    empty = 0

    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            empty += 1
        else:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    print(f"\n[{split.upper()}] {len(images)} images")
    for cid, cnt in sorted(class_counts.items()):
        print(f"  {CLASS_NAMES[cid]:10s}: {cnt}")
    print(f"  {'empty':10s}: {empty}")
    total_images += len(images)

print(f"\nTOTAL: {total_images} images")
print("────────────────────────────────────────────")

import shutil
import random
from pathlib import Path

random.seed(42)

BALANCED_DIR = Path('/content/balanced')

train_img = BALANCED_DIR / 'train' / 'images'
train_lbl = BALANCED_DIR / 'train' / 'labels'
test_img  = BALANCED_DIR / 'test' / 'images'
test_lbl  = BALANCED_DIR / 'test' / 'labels'

# Find empty frames in train
empty_in_train = []
for lbl in train_lbl.glob('*.txt'):
    if lbl.stat().st_size == 0:
        img = train_img / (lbl.stem + '.jpg')
        if img.exists():
            empty_in_train.append((img, lbl))

print(f"Empty frames in train: {len(empty_in_train)}")

# Move 30 to test (17 + 30 = 47, same as val)
to_move = random.sample(empty_in_train, 30)
for img, lbl in to_move:
    shutil.move(str(img), test_img / img.name)
    shutil.move(str(lbl), test_lbl / lbl.name)

print(f"✓ Moved 30 empty frames to test")
print(f"Train empty frames remaining: {len(empty_in_train) - 30}")
print(f"Test empty frames now: 47")

from pathlib import Path
from collections import Counter

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

print("── Final Balanced Dataset Verification ─────")
total_images = 0

for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'

    images = list(img_dir.glob('*.jpg'))
    class_counts = Counter()
    empty = 0

    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            empty += 1
        else:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    print(f"\n[{split.upper()}] {len(images)} images")
    for cid, cnt in sorted(class_counts.items()):
        print(f"  {CLASS_NAMES[cid]:10s}: {cnt}")
    print(f"  {'empty':10s}: {empty}")
    total_images += len(images)

print(f"\nTOTAL: {total_images} images")
print("────────────────────────────────────────────")

import shutil
import random
from pathlib import Path

random.seed(99)

BALANCED_DIR = Path('/content/balanced')

train_img = BALANCED_DIR / 'train' / 'images'
train_lbl = BALANCED_DIR / 'train' / 'labels'
test_img  = BALANCED_DIR / 'test' / 'images'
test_lbl  = BALANCED_DIR / 'test' / 'labels'

empty_in_test = []
for lbl in test_lbl.glob('*.txt'):
    if lbl.stat().st_size == 0:
        img = test_img / (lbl.stem + '.jpg')
        if img.exists():
            empty_in_test.append((img, lbl))

print(f"Empty frames in test: {len(empty_in_test)}")

to_move = random.sample(empty_in_test, 60)
for img, lbl in to_move:
    shutil.move(str(img), train_img / img.name)
    shutil.move(str(lbl), train_lbl / lbl.name)

print(f"✓ Moved 60 back to train")
print(f"Test empty frames now: {len(empty_in_test) - 60}")

from pathlib import Path
from collections import Counter

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

print("── Final Balanced Dataset Verification ─────")
total_images = 0

for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'

    images = list(img_dir.glob('*.jpg'))
    class_counts = Counter()
    empty = 0

    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            empty += 1
        else:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    print(f"\n[{split.upper()}] {len(images)} images")
    for cid, cnt in sorted(class_counts.items()):
        print(f"  {CLASS_NAMES[cid]:10s}: {cnt}")
    print(f"  {'empty':10s}: {empty}")
    total_images += len(images)

print(f"\nTOTAL: {total_images} images")
print("────────────────────────────────────────────")

import random
from pathlib import Path
from collections import Counter

random.seed(42)

BALANCED_DIR = Path('/content/balanced')
train_img = BALANCED_DIR / 'train' / 'images'
train_lbl = BALANCED_DIR / 'train' / 'labels'

# Separate single-boar and multi-boar images
single_boar = []
multi_boar = []

for lbl in train_lbl.glob('*.txt'):
    content = lbl.read_text().strip()
    if not content:
        continue
    lines = [l for l in content.split('\n') if l.strip()]
    classes = [int(l.split()[0]) for l in lines]

    if 1 not in classes:  # not a boar image
        continue

    boar_count = classes.count(1)
    img = train_img / (lbl.stem + '.jpg')
    if not img.exists():
        continue

    if boar_count == 1:
        single_boar.append((img, lbl))
    else:
        multi_boar.append((img, lbl))

print(f"Single boar images: {len(single_boar)}")
print(f"Multi boar images:  {len(multi_boar)}")
print(f"Total boar images:  {len(single_boar) + len(multi_boar)}")

# Keep all single boar, remove most multi boar
# Target: ~1,300 total boar annotations
to_keep_multi = random.sample(multi_boar, min(100, len(multi_boar)))
to_remove = [x for x in multi_boar if x not in to_keep_multi]

print(f"\nRemoving {len(to_remove)} multi-boar images...")
for img, lbl in to_remove:
    img.unlink()
    lbl.unlink()

print(f"✓ Done. Kept {len(single_boar) + len(to_keep_multi)} boar images")

import random
import shutil
from pathlib import Path

random.seed(42)

BALANCED_DIR = Path('/content/balanced')
test_img = BALANCED_DIR / 'test' / 'images'
test_lbl = BALANCED_DIR / 'test' / 'labels'

CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}
TARGET = 80

def get_images_by_class(target_class):
    result = []
    for lbl in test_lbl.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            continue
        classes = [int(l.split()[0]) for l in content.split('\n') if l.strip()]
        if target_class in classes:
            img = test_img / (lbl.stem + '.jpg')
            if img.exists():
                result.append((img, lbl))
    return result

for target_class in [0, 1]:  # deer and boar only — rabbit/jackal/pheasant already low
    species = CLASS_NAMES[target_class]
    images = get_images_by_class(target_class)
    current = len(images)

    if current <= TARGET:
        print(f"{species}: already at {current}, skipping")
        continue

    to_remove = random.sample(images, current - TARGET)
    for img, lbl in to_remove:
        img.unlink()
        lbl.unlink()

    print(f"✓ {species}: {current} → {TARGET}")

print("\n✓ Test balancing done!")

from pathlib import Path
from collections import Counter

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

print("── Final Balanced Dataset Verification ─────")
total_images = 0

for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'

    images = list(img_dir.glob('*.jpg'))
    class_counts = Counter()
    empty = 0

    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            empty += 1
        else:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    print(f"\n[{split.upper()}] {len(images)} images")
    for cid, cnt in sorted(class_counts.items()):
        print(f"  {CLASS_NAMES[cid]:10s}: {cnt}")
    print(f"  {'empty':10s}: {empty}")
    total_images += len(images)

print(f"\nTOTAL: {total_images} images")
print("────────────────────────────────────────────")

import random
from pathlib import Path

random.seed(42)

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

def get_images_by_class(split, target_class):
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'
    result = []
    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            continue
        classes = [int(l.split()[0]) for l in content.split('\n') if l.strip()]
        if target_class in classes:
            img = img_dir / (lbl.stem + '.jpg')
            if img.exists():
                result.append((img, lbl))
    return result

# Fix test only — downsample boar and deer to 60
print("[TEST]")
for cid in [0, 1]:
    imgs = get_images_by_class('test', cid)
    print(f"  {CLASS_NAMES[cid]}: {len(imgs)} images")
    if len(imgs) > 60:
        to_remove = random.sample(imgs, len(imgs) - 60)
        for img, lbl in to_remove:
            img.unlink()
            lbl.unlink()
        print(f"  ✓ {CLASS_NAMES[cid]}: {len(imgs)} → 60")
    else:
        print(f"  {CLASS_NAMES[cid]}: already at {len(imgs)}, skipping")

print("\n✓ Done!")

from pathlib import Path
from collections import Counter

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

print("── Final Balanced Dataset Verification ─────")
total_images = 0

for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'

    images = list(img_dir.glob('*.jpg'))
    class_counts = Counter()
    empty = 0

    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            empty += 1
        else:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    print(f"\n[{split.upper()}] {len(images)} images")
    for cid, cnt in sorted(class_counts.items()):
        print(f"  {CLASS_NAMES[cid]:10s}: {cnt}")
    print(f"  {'empty':10s}: {empty}")
    total_images += len(images)

print(f"\nTOTAL: {total_images} images")
print("────────────────────────────────────────────")

import shutil
import random
from pathlib import Path

random.seed(42)

BALANCED_DIR = Path('/content/balanced')

train_img = BALANCED_DIR / 'train' / 'images'
train_lbl = BALANCED_DIR / 'train' / 'labels'
val_img   = BALANCED_DIR / 'val' / 'images'
val_lbl   = BALANCED_DIR / 'val' / 'labels'
test_img  = BALANCED_DIR / 'test' / 'images'
test_lbl  = BALANCED_DIR / 'test' / 'labels'

def get_boar_images(img_dir, lbl_dir):
    result = []
    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            continue
        classes = [int(l.split()[0]) for l in content.split('\n') if l.strip()]
        if 1 in classes:
            img = img_dir / (lbl.stem + '.jpg')
            if img.exists():
                result.append((img, lbl))
    return result

# Move 30 boar from val to train
val_boar = get_boar_images(val_img, val_lbl)
to_move_val = random.sample(val_boar, 30)
for img, lbl in to_move_val:
    shutil.move(str(img), train_img / img.name)
    shutil.move(str(lbl), train_lbl / lbl.name)
print(f"✓ Moved 30 boar from val to train")

# Move 20 boar from test to train
test_boar = get_boar_images(test_img, test_lbl)
to_move_test = random.sample(test_boar, 20)
for img, lbl in to_move_test:
    shutil.move(str(img), train_img / img.name)
    shutil.move(str(lbl), train_lbl / lbl.name)
print(f"✓ Moved 20 boar from test to train")

print(f"\n✓ Done! Run verification to check.")

from pathlib import Path
from collections import Counter

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

print("── Final Balanced Dataset Verification ─────")
total_images = 0

for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'

    images = list(img_dir.glob('*.jpg'))
    class_counts = Counter()
    empty = 0

    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            empty += 1
        else:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    print(f"\n[{split.upper()}] {len(images)} images")
    for cid, cnt in sorted(class_counts.items()):
        print(f"  {CLASS_NAMES[cid]:10s}: {cnt}")
    print(f"  {'empty':10s}: {empty}")
    total_images += len(images)

print(f"\nTOTAL: {total_images} images")
print("────────────────────────────────────────────")

import matplotlib.pyplot as plt
from pathlib import Path
from collections import Counter

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('Balanced Dataset — Class Distribution', fontsize=14)

for i, split in enumerate(['train', 'val', 'test']):
    lbl_dir = BALANCED_DIR / split / 'labels'
    img_dir = BALANCED_DIR / split / 'images'

    class_counts = Counter()
    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if content:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    species = [CLASS_NAMES[k] for k in sorted(class_counts.keys())]
    counts  = [class_counts[k] for k in sorted(class_counts.keys())]
    total_images = len(list(img_dir.glob('*.jpg')))

    bars = axes[i].bar(species, counts,
                       color=['#2196F3','#4CAF50','#FF9800','#F44336','#9C27B0'])
    axes[i].set_title(f'{split.upper()} — {total_images} images')
    axes[i].set_ylabel('Annotations')
    axes[i].tick_params(axis='x', rotation=45)

    for bar, count in zip(bars, counts):
        axes[i].text(bar.get_x() + bar.get_width()/2,
                    bar.get_height() + 5,
                    str(count), ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/ForestLens/eda_balanced_distribution.png', dpi=150)
plt.show()
print("✓ EDA chart saved to Google Drive")

import cv2
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import random

random.seed(42)

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}
train_img = BALANCED_DIR / 'train' / 'images'
train_lbl = BALANCED_DIR / 'train' / 'labels'

# ── 1. Resolution distribution ────────────────────────────────
print("Checking resolutions...")
widths, heights = [], []
sample_imgs = random.sample(list(train_img.glob('*.jpg')), 500)
for img_path in sample_imgs:
    img = cv2.imread(str(img_path))
    if img is not None:
        h, w = img.shape[:2]
        widths.append(w)
        heights.append(h)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].hist(widths, bins=20, color='#2196F3')
axes[0].set_title('Width distribution')
axes[0].set_xlabel('Pixels')
axes[1].hist(heights, bins=20, color='#4CAF50')
axes[1].set_title('Height distribution')
axes[1].set_xlabel('Pixels')
plt.suptitle('Image Resolution Distribution (500 sample)')
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/ForestLens/eda_resolution.png', dpi=150)
plt.show()
print(f"  Width:  min={min(widths)} max={max(widths)} avg={int(np.mean(widths))}")
print(f"  Height: min={min(heights)} max={max(heights)} avg={int(np.mean(heights))}")

# ── 2. Brightness distribution ────────────────────────────────
print("\nChecking brightness...")
brightness = []
for img_path in sample_imgs:
    img = cv2.imread(str(img_path), cv2.IMREAD_GRAYSCALE)
    if img is not None:
        brightness.append(np.mean(img))

plt.figure(figsize=(10, 4))
plt.hist(brightness, bins=30, color='#FF9800')
plt.title('Brightness Distribution (after CLAHE normalization)')
plt.xlabel('Mean brightness')
plt.ylabel('Count')
plt.savefig('/content/drive/MyDrive/ForestLens/eda_brightness.png', dpi=150)
plt.show()
print(f"  Brightness: min={min(brightness):.1f} max={max(brightness):.1f} avg={np.mean(brightness):.1f}")

# ── 3. Sample images per class ────────────────────────────────
print("\nSampling images per class...")
fig, axes = plt.subplots(5, 3, figsize=(12, 18))
fig.suptitle('Sample Images per Species', fontsize=14)

for class_id in range(5):
    class_imgs = []
    for lbl in train_lbl.glob('*.txt'):
        content = lbl.read_text().strip()
        if content and any(int(l.split()[0]) == class_id
                          for l in content.split('\n') if l.strip()):
            img = train_img / (lbl.stem + '.jpg')
            if img.exists():
                class_imgs.append(img)

    samples = random.sample(class_imgs, min(3, len(class_imgs)))
    for j, img_path in enumerate(samples):
        img = cv2.imread(str(img_path))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        axes[class_id][j].imshow(img)
        axes[class_id][j].axis('off')
        if j == 0:
            axes[class_id][j].set_ylabel(CLASS_NAMES[class_id], fontsize=12)

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/ForestLens/eda_samples.png', dpi=150)
plt.show()

# ── 4. Augmentation quality check ────────────────────────────
print("\nChecking augmented images...")
aug_imgs = [f for f in train_img.glob('aug_*.jpg')]
print(f"  Total augmented images: {len(aug_imgs)}")
sample_aug = random.sample(aug_imgs, min(6, len(aug_imgs)))

fig, axes = plt.subplots(2, 3, figsize=(12, 8))
fig.suptitle('Augmented Images Sample', fontsize=14)
for i, img_path in enumerate(sample_aug):
    img = cv2.imread(str(img_path))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    axes[i//3][i%3].imshow(img)
    axes[i//3][i%3].axis('off')
    axes[i//3][i%3].set_title(img_path.name[:30])
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/ForestLens/eda_augmented.png', dpi=150)
plt.show()

# ── 5. Empty frames check ─────────────────────────────────────
print("\nChecking empty frames...")
empty_imgs = []
for lbl in train_lbl.glob('*.txt'):
    if lbl.stat().st_size == 0:
        img = train_img / (lbl.stem + '.jpg')
        if img.exists():
            empty_imgs.append(img)

sample_empty = random.sample(empty_imgs, min(6, len(empty_imgs)))
fig, axes = plt.subplots(2, 3, figsize=(12, 8))
fig.suptitle('Empty Frames Sample', fontsize=14)
for i, img_path in enumerate(sample_empty):
    img = cv2.imread(str(img_path))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    axes[i//3][i%3].imshow(img)
    axes[i//3][i%3].axis('off')
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/ForestLens/eda_empty_frames.png', dpi=150)
plt.show()

print("\n✓ All EDA steps complete! Charts saved to Google Drive")

import cv2
from pathlib import Path
from tqdm import tqdm

BALANCED_DIR = Path('/content/balanced')

print("Resizing all images to 640x640...")

for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    images = list(img_dir.glob('*.jpg'))
    resized = 0

    for img_path in tqdm(images, desc=split):
        img = cv2.imread(str(img_path))
        if img is None:
            continue
        h, w = img.shape[:2]
        if h != 640 or w != 640:
            img = cv2.resize(img, (640, 640))
            cv2.imwrite(str(img_path), img)
            resized += 1

    print(f"  [{split}] Resized {resized}/{len(images)} images")

print("\n✓ All images are now 640x640")

from ultralytics import YOLO
from pathlib import Path
import random

random.seed(42)

BALANCED_DIR = Path('/content/balanced')
model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

# Check jackal and rabbit images
# If model detects a completely different species with high confidence → likely mislabeled
bad_images = []

for split in ['train']:  # only clean train
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'

    # Get jackal and rabbit images
    for target_class in [2, 3]:  # rabbit, jackal
        species = CLASS_NAMES[target_class]
        count = 0
        removed = 0

        for lbl in lbl_dir.glob('*.txt'):
            content = lbl.read_text().strip()
            if not content:
                continue
            classes = [int(l.split()[0]) for l in content.split('\n') if l.strip()]
            if target_class not in classes:
                continue

            img = img_dir / (lbl.stem + '.jpg')
            if not img.exists():
                continue

            count += 1
            result = model.predict(str(img), conf=0.3, verbose=False)[0]

            # If model detects nothing at all → likely bad image
            if len(result.boxes) == 0:
                bad_images.append((img, lbl, species))
                removed += 1

        print(f"  {species}: {count} images, {removed} flagged as bad")

print(f"\nTotal flagged: {len(bad_images)}")
print("Sample bad images:")
for img, lbl, species in bad_images[:5]:
    print(f"  {species}: {img.name}")

from pathlib import Path

print(f"Removing {len(bad_images)} bad images...")

removed = 0
for img, lbl, species in bad_images:
    if img.exists():
        img.unlink()
    if lbl.exists():
        lbl.unlink()
    removed += 1

print(f"✓ Removed {removed} bad images")
print(f"  Rabbit removed: {sum(1 for _, _, s in bad_images if s == 'rabbit')}")
print(f"  Jackal removed: {sum(1 for _, _, s in bad_images if s == 'jackal')}")

from pathlib import Path
from collections import Counter

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

print("── Dataset After Cleaning ─────────────────")
total_images = 0

for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'

    images = list(img_dir.glob('*.jpg'))
    class_counts = Counter()
    empty = 0

    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            empty += 1
        else:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    print(f"\n[{split.upper()}] {len(images)} images")
    for cid, cnt in sorted(class_counts.items()):
        print(f"  {CLASS_NAMES[cid]:10s}: {cnt}")
    print(f"  {'empty':10s}: {empty}")
    total_images += len(images)

print(f"\nTOTAL: {total_images} images")
print("────────────────────────────────────────────")

from ultralytics import YOLO
from pathlib import Path
import shutil
import random

random.seed(42)

BALANCED_DIR = Path('/content/balanced')
RAW_DIR = Path('/content/drive/MyDrive/ForestLens/Data/raw')
model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens2/weights/best.pt')

# Step 1 — Delete all current empty frames
print("Removing all current empty frames...")
total_removed = 0
for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'
    removed = 0
    for lbl in lbl_dir.glob('*.txt'):
        if lbl.stat().st_size == 0:
            img = img_dir / (lbl.stem + '.jpg')
            if img.exists():
                img.unlink()
            lbl.unlink()
            removed += 1
    print(f"  [{split}] Removed {removed} empty frames")
    total_removed += removed
print(f"  Total removed: {total_removed}")

# Step 2 — Collect clean empty frames from raw datasets
# Only keep images where model confirms NO animal present
print("\nCollecting clean empty frames...")

TARGETS = {'train': 400, 'val': 50, 'test': 50}
collected = {'train': [], 'val': [], 'test': []}

for dataset in ['Boar-Deer-Hare-Coyote', 'hare', 'Coyote', 'pheasant']:
    for src_split, dst_split in [('train', 'train'), ('valid', 'val'), ('test', 'test')]:

        if all(len(collected[s]) >= TARGETS[s] for s in TARGETS):
            break

        lbl_src = RAW_DIR / dataset / src_split / 'labels'
        img_src = RAW_DIR / dataset / src_split / 'images'

        if not lbl_src.exists():
            continue

        empty_files = [l for l in lbl_src.glob('*.txt') if l.stat().st_size == 0]
        random.shuffle(empty_files)

        for lbl in empty_files:
            if len(collected[dst_split]) >= TARGETS[dst_split]:
                break

            img = img_src / (lbl.stem + '.jpg')
            if not img.exists():
                img = img_src / (lbl.stem + '.png')
            if not img.exists():
                continue

            # Verify with model — only keep if truly empty
            result = model.predict(str(img), conf=0.3, verbose=False)[0]
            if len(result.boxes) == 0:
                collected[dst_split].append((img, lbl))

print(f"  Collected: train={len(collected['train'])} val={len(collected['val'])} test={len(collected['test'])}")

# Step 3 — Copy verified empty frames
print("\nCopying verified empty frames...")
for split, items in collected.items():
    dst_img = BALANCED_DIR / split / 'images'
    dst_lbl = BALANCED_DIR / split / 'labels'

    for img, lbl in items:
        new_name = f"empty_{split}_{img.name}"
        # Resize to 640x640
        import cv2
        image = cv2.imread(str(img))
        if image is not None:
            image = cv2.resize(image, (640, 640))
            cv2.imwrite(str(dst_img / new_name), image)
            (dst_lbl / new_name.replace('.jpg', '.txt').replace('.png', '.txt')).write_text('')

    print(f"  [{split}] Added {len(items)} clean empty frames")

print("\n✓ Empty frames replaced with clean verified ones!")

from pathlib import Path
from collections import Counter

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

print("── Final Clean Dataset Verification ────────")
total_images = 0

for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'

    images = list(img_dir.glob('*.jpg'))
    class_counts = Counter()
    empty = 0

    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            empty += 1
        else:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    print(f"\n[{split.upper()}] {len(images)} images")
    for cid, cnt in sorted(class_counts.items()):
        print(f"  {CLASS_NAMES[cid]:10s}: {cnt}")
    print(f"  {'empty':10s}: {empty}")
    total_images += len(images)

print(f"\nTOTAL: {total_images} images")
print("────────────────────────────────────────────")

import shutil
import random
from pathlib import Path

random.seed(42)

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

train_img = BALANCED_DIR / 'train' / 'images'
train_lbl = BALANCED_DIR / 'train' / 'labels'
test_img  = BALANCED_DIR / 'test' / 'images'
test_lbl  = BALANCED_DIR / 'test' / 'labels'

TARGET = 100  # target per class in test

def get_class_images(img_dir, lbl_dir, target_class):
    result = []
    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            continue
        classes = [int(l.split()[0]) for l in content.split('\n') if l.strip()]
        if target_class in classes:
            img = img_dir / (lbl.stem + '.jpg')
            if img.exists():
                result.append((img, lbl))
    return result

def count_class(lbl_dir, target_class):
    count = 0
    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if content and any(int(l.split()[0]) == target_class
                          for l in content.split('\n') if l.strip()):
            count += 1
    return count

# Move images from train to test for underrepresented classes
for cid in range(5):
    species = CLASS_NAMES[cid]
    current = count_class(test_lbl, cid)
    needed = TARGET - current

    if needed <= 0:
        print(f"{species}: already at {current}, skipping")
        continue

    train_imgs = get_class_images(train_img, train_lbl, cid)
    to_move = random.sample(train_imgs, min(needed, len(train_imgs)))

    for img, lbl in to_move:
        shutil.move(str(img), test_img / img.name)
        shutil.move(str(lbl), test_lbl / lbl.name)

    print(f"✓ {species}: {current} → {current + len(to_move)}")

# Move empty frames from train to test
empty_in_train = []
for lbl in train_lbl.glob('*.txt'):
    if lbl.stat().st_size == 0:
        img = train_img / (lbl.stem + '.jpg')
        if img.exists():
            empty_in_train.append((img, lbl))

current_empty = sum(1 for l in test_lbl.glob('*.txt') if l.stat().st_size == 0)
needed_empty = 40 - current_empty

if needed_empty > 0:
    to_move = random.sample(empty_in_train, min(needed_empty, len(empty_in_train)))
    for img, lbl in to_move:
        shutil.move(str(img), test_img / img.name)
        shutil.move(str(lbl), test_lbl / lbl.name)
    print(f"✓ empty: {current_empty} → {current_empty + len(to_move)}")

print("\n✓ Test set boosted!")

from pathlib import Path
from collections import Counter

BALANCED_DIR = Path('/content/balanced')
CLASS_NAMES = {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}

print("── Final Clean Dataset Verification ────────")
total_images = 0

for split in ['train', 'val', 'test']:
    img_dir = BALANCED_DIR / split / 'images'
    lbl_dir = BALANCED_DIR / split / 'labels'

    images = list(img_dir.glob('*.jpg'))
    class_counts = Counter()
    empty = 0

    for lbl in lbl_dir.glob('*.txt'):
        content = lbl.read_text().strip()
        if not content:
            empty += 1
        else:
            for line in content.split('\n'):
                if line.strip():
                    class_counts[int(line.split()[0])] += 1

    print(f"\n[{split.upper()}] {len(images)} images")
    for cid, cnt in sorted(class_counts.items()):
        print(f"  {CLASS_NAMES[cid]:10s}: {cnt}")
    print(f"  {'empty':10s}: {empty}")
    total_images += len(images)

print(f"\nTOTAL: {total_images} images")
print("────────────────────────────────────────────")

import shutil
import yaml
from pathlib import Path

print("Saving to Google Drive...")
shutil.copytree(
    '/content/balanced',
    '/content/drive/MyDrive/ForestLens/Data/balanced',
    dirs_exist_ok=True
)

config = {
    'path': '/content/balanced',
    'train': 'train/images',
    'val':   'val/images',
    'test':  'test/images',
    'nc': 5,
    'names': {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}
}

with open('/content/balanced_dataset.yaml', 'w') as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)

shutil.copy(
    '/content/balanced_dataset.yaml',
    '/content/drive/MyDrive/ForestLens/Data/balanced_dataset.yaml'
)

print("✓ Everything saved to Google Drive")

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

model.tune(
    data       = '/content/balanced_dataset.yaml',
    epochs     = 10,
    iterations = 30,
    imgsz      = 640,
    device     = 0,
    project    = '/content/drive/MyDrive/ForestLens/runs',
    name       = 'forest_lens_tune',
    save       = True,
)

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

results = model.train(
    data         = '/content/balanced_dataset.yaml',
    epochs       = 80,
    imgsz        = 640,
    batch        = 16,
    patience     = 15,
    project      = '/content/drive/MyDrive/ForestLens/runs',
    name         = 'forest_lens_v2',
    device       = 0,
    save         = True,
    save_period  = 5,
    lr0          = 0.001,
    lrf          = 0.01,
    momentum     = 0.937,
    weight_decay = 0.0005,
    warmup_epochs= 3,
    mixup        = 0.15,
    cos_lr       = True,
    close_mosaic = 10,
    hsv_h        = 0.015,
    hsv_s        = 0.7,
    hsv_v        = 0.4,
    fliplr       = 0.5,
    mosaic       = 1.0,
    rect         = False,
)

print("✓ Training complete!")

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens_v2/weights/best.pt')

results = model.val(
    data   = '/content/balanced_dataset.yaml',
    split  = 'test',
    device = 'cpu',
)

print("✓ Evaluation complete!")

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics -q

import shutil
shutil.copytree('/content/drive/MyDrive/ForestLens/Data/balanced', '/content/balanced', dirs_exist_ok=True)
print("✓ Data ready")

from ultralytics import YOLO
import matplotlib.pyplot as plt
from pathlib import Path
import random

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens_v2/weights/best.pt')

test_images = list(Path('/content/balanced/test/images').glob('*.jpg'))
samples = random.sample(test_images, 5)

for img_path in samples:
    results = model.predict(str(img_path), conf=0.35, verbose=False)
    result = results[0]

    detections = [(model.names[int(b.cls[0])], f"{float(b.conf[0]):.0%}")
                  for b in result.boxes]

    plt.figure(figsize=(10, 6))
    plt.imshow(result.plot()[:,:,::-1])
    plt.axis('off')
    plt.title(str(detections if detections else 'empty frame'))
    plt.show()

from ultralytics import YOLO
import matplotlib.pyplot as plt
from pathlib import Path
import random

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens_v2/weights/best.pt')

# Get only deer images from test
test_labels = Path('/content/balanced/test/labels')
test_images = Path('/content/balanced/test/images')

deer_images = []
for lbl in test_labels.glob('*.txt'):
    content = lbl.read_text().strip()
    if content and any(int(l.split()[0]) == 0 for l in content.split('\n') if l.strip()):
        img = test_images / (lbl.stem + '.jpg')
        if img.exists():
            deer_images.append(img)

print(f"Found {len(deer_images)} deer images in test set")
sample = random.choice(deer_images)

results = model.predict(str(sample), conf=0.35, verbose=False)
result = results[0]

for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

plt.figure(figsize=(10, 6))
plt.imshow(result.plot()[:,:,::-1])
plt.axis('off')
plt.show()

from ultralytics import YOLO
import matplotlib.pyplot as plt
from pathlib import Path
import random

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens_v2/weights/best.pt')

test_images = list(Path('/content/balanced/test/images').glob('*.jpg'))
samples = random.sample(test_images, 20)

for i, img_path in enumerate(samples):
    results = model.predict(str(img_path), conf=0.35, verbose=False)
    result = results[0]

    detections = [(model.names[int(b.cls[0])], f"{float(b.conf[0]):.0%}")
                  for b in result.boxes]

    plt.figure(figsize=(10, 6))
    plt.imshow(result.plot()[:,:,::-1])
    plt.axis('off')
    plt.title(f"Image {i+1}: {detections if detections else 'empty frame'}")
    plt.show()

import shutil
shutil.copytree('/content/drive/MyDrive/ForestLens/Data/balanced', '/content/balanced', dirs_exist_ok=True)
print("✓ Data ready")

import yaml
config = {
    'path': '/content/balanced',
    'train': 'train/images',
    'val': 'val/images',
    'test': 'test/images',
    'nc': 5,
    'names': {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}
}
with open('/content/balanced_dataset.yaml', 'w') as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)
print("✓ YAML ready")

from ultralytics import YOLO
import matplotlib.pyplot as plt
from pathlib import Path
import random

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens_v2/weights/best.pt')

test_images = list(Path('/content/balanced/test/images').glob('*.jpg'))
samples = random.sample(test_images, 20)

for i, img_path in enumerate(samples):
    results = model.predict(str(img_path), conf=0.35, verbose=False)
    result = results[0]

    detections = [(model.names[int(b.cls[0])], f"{float(b.conf[0]):.0%}")
                  for b in result.boxes]

    plt.figure(figsize=(10, 6))
    plt.imshow(result.plot()[:,:,::-1])
    plt.axis('off')
    plt.title(f"Image {i+1}: {detections if detections else 'empty frame'}")
    plt.show()

from PIL import Image
import matplotlib.pyplot as plt
from ultralytics import YOLO

# Convert jfif to jpg
img = Image.open('/content/download.jfif')
img.save('/content/download.jpg')
print("✓ Converted to jpg")

# Run detection
model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens_v2/weights/best.pt')

results = model.predict(
    source  = '/content/download.jpg',
    conf    = 0.35,
    verbose = False
)

result = results[0]
print(f"Detections: {len(result.boxes)}")
for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

plt.figure(figsize=(10, 6))
plt.imshow(result.plot()[:,:,::-1])
plt.axis('off')
plt.show()

results = model.predict(
    source  = '/content/download.jpg',
    conf    = 0.01,
    verbose = False
)

result = results[0]
print(f"Detections at conf=0.01: {len(result.boxes)}")
for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

import cv2
import numpy as np
from PIL import Image
from ultralytics import YOLO
import matplotlib.pyplot as plt

# Load image
img = cv2.imread('/content/download.jpg')

# Step 1 — Resize to 640x640
img = cv2.resize(img, (640, 640))

# Step 2 — Convert to grayscale and back (simulate IR trail cam)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_gray = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)

# Step 3 — Apply CLAHE (same normalization as our dataset)
lab = cv2.cvtColor(img_gray, cv2.COLOR_BGR2LAB)
l, a, b = cv2.split(lab)
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
l = clahe.apply(l)
lab = cv2.merge([l, a, b])
normalized = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)

# Save processed image
cv2.imwrite('/content/download_processed.jpg', normalized)
print("✓ Image processed")

# Run detection
model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens_v2/weights/best.pt')

results = model.predict(
    source  = '/content/download_processed.jpg',
    conf    = 0.35,
    verbose = False
)

result = results[0]
print(f"Detections: {len(result.boxes)}")
for box in result.boxes:
    species = model.names[int(box.cls[0])]
    confidence = float(box.conf[0])
    print(f"  → {species}: {confidence:.2%} confidence")

plt.figure(figsize=(10, 6))
plt.imshow(result.plot()[:,:,::-1])
plt.axis('off')
plt.show()

from ultralytics import YOLO
import yaml

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens_v2/weights/best.pt')

config = {
    'path': '/content/balanced',
    'train': 'train/images',
    'val': 'val/images',
    'test': 'test/images',
    'nc': 5,
    'names': {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}
}

with open('/content/balanced_dataset.yaml', 'w') as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)

results = model.val(
    data    = '/content/balanced_dataset.yaml',
    split   = 'test',
    device  = 'cpu',
)

print("✓ Evaluation complete!")

import json
import shutil
from pathlib import Path

# Save metrics
results_v2 = {
    "model": "forest_lens_v2",
    "test_set": "balanced (540 images)",
    "overall": {
        "precision": 0.915,
        "recall": 0.921,
        "mAP50": 0.948,
        "mAP50_95": 0.747
    },
    "per_class": {
        "deer":     {"precision": 0.889, "recall": 0.899, "mAP50": 0.918, "mAP50_95": 0.739},
        "boar":     {"precision": 0.868, "recall": 0.866, "mAP50": 0.914, "mAP50_95": 0.685},
        "rabbit":   {"precision": 0.896, "recall": 0.943, "mAP50": 0.953, "mAP50_95": 0.654},
        "jackal":   {"precision": 0.971, "recall": 0.903, "mAP50": 0.966, "mAP50_95": 0.824},
        "pheasant": {"precision": 0.950, "recall": 0.991, "mAP50": 0.988, "mAP50_95": 0.834}
    }
}

out = Path('/content/drive/MyDrive/ForestLens/evaluation_results_v2.json')
with open(out, 'w') as f:
    json.dump(results_v2, f, indent=2)

# Also copy the val results plots
shutil.copytree(
    '/content/runs/detect/val',
    '/content/drive/MyDrive/ForestLens/test_evaluation_v2',
    dirs_exist_ok=True
)

print("✓ Results saved to Google Drive")
print("✓ Evaluation plots saved to Google Drive")

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics -q

import shutil
shutil.copytree('/content/drive/MyDrive/ForestLens/Data/balanced', '/content/balanced', dirs_exist_ok=True)
print("✓ Data ready")

from ultralytics import YOLO
model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens_v2/weights/best.pt')
print("✓ Model ready")

from ultralytics import YOLO
import yaml
from pathlib import Path

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens_v2/weights/best.pt')

# Write yaml
config = {
    'path': '/content/balanced',
    'train': 'train/images',
    'val': 'val/images',
    'test': 'test/images',
    'nc': 5,
    'names': {0: 'deer', 1: 'boar', 2: 'rabbit', 3: 'jackal', 4: 'pheasant'}
}
with open('/content/balanced_dataset.yaml', 'w') as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)

# Run evaluation on test set
results = model.val(
    data   = '/content/balanced_dataset.yaml',
    split  = 'test',
    device = 'cpu',
)

print("✓ Evaluation complete!")

from ultralytics import YOLO
import matplotlib.pyplot as plt
from pathlib import Path
import random

model = YOLO('/content/drive/MyDrive/ForestLens/runs/forest_lens_v2/weights/best.pt')

test_images = list(Path('/content/balanced/test/images').glob('*.jpg'))
random.shuffle(test_images)

for i, img_path in enumerate(test_images[:20]):
    results = model.predict(str(img_path), conf=0.35, verbose=False)
    result = results[0]

    if len(result.boxes) == 0:
        continue

    detections = [(model.names[int(b.cls[0])], f"{float(b.conf[0]):.0%}")
                  for b in result.boxes]

    plt.figure(figsize=(8, 6))
    plt.imshow(result.plot()[:,:,::-1])
    plt.axis('off')
    plt.title(str(detections))
    plt.show()

    print(f"Image {i+1}: {detections}")

